import { Toaster } from "react-hot-toast";
import "./globals.css";
import { Quicksand } from "next/font/google";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata = {
  title: "Huba Ferencz | Front-end Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.className} bg-white text-white dark:bg-black`}
      >
        {children}
        <Toaster
          toastOptions={{
            style: {
              padding: "10px",
              color: "#1C1C1E",
              background: "#A6FE05",
              fontWeight: "600",
              fontSize: "20px",
            },
          }}
        />
      </body>
    </html>
  );
}
